name: ide
channels:
    - defaults
    - conda-forge
dependencies:
    - pip
    - rise
    - voila
    - black
    - qgrid
    - nbdime
    - nbformat
    - nb_conda
    - jupytext
    - papermill
    - nbconvert
    - ipywidgets
    - jupyterlab
    - ipyparallel
    - nodejs>=13.8
    - nteract-scrapbook
    - jedi<0.16,>=0.14.1
    - pip:
        - kedro
        - jupyterlab-git
        - jupyterlab-quickopen
        - jupyterlab_code_formatter
