name: ide
channels:
    - defaults
    - conda-forge
dependencies:
    - pip
    - rise
    - voila
    - black
    - nodejs
    - nbdime
    - nb_conda
    - jupytext
    - papermill
    - ipywidgets
    - jupyterlab
    - ipyparallel
    - pip:
        - jupyter-lsp
        - jupyterlab-quickopen
        - jupyterlab_code_formatter
        - python-language-server