name: ide
channels:
    - defaults
    - conda-forge
dependencies:
    - pip
    - rise
    - rope
    - nbval
    - voila
    - black
    - pylint
    - nbdime
    - nbformat
    - nb_conda
    - jupytext
    - nbpresent
    - papermill
    - nbconvert
    - ipywidgets
    - jupyterlab
    - ipyparallel
    - nodejs>=13.8
    - nb_anacondacloud
    - jedi<0.16,>=0.14.1
    - pip:
        - jupyter-lsp
        - jupyterlab-git
        - jupyterlab-quickopen
        - jupyterlab_code_formatter
        - python-language-server
